blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'portfolio'

urlpatterns = [
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sharifli_com/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('portfolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images/', default='blog/images/6.jpg')
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)


    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
from django.core.paginator import Paginator


def all_blogs(request):
    blog_list = Blog.objects.all()
    paginator = Paginator(blog_list, 10)  # Set the number of items per page
    page = request.GET.get('page')
    blogs = paginator.get_page(page)
    # commented by hsh blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})


# Create your views here.
def project_detail(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    context = {'project': project}
    return render(request, 'portfolio/project.html', context)

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}



<section data-bs-version="5.1" class="features3 cid-tA3VKVutDo" id="features3-x">
 <link rel="stylesheet" href="{% static "css/styles.css" %}">

    <div class="container">
        <div class="mbr-section-head ">
            <h4 class="mbr-section-title mbr-fonts-style align-center mb-3 mt-6 display-2">
                <strong>Features</strong></h4>
            <h5 class="mbr-section-subtitle mbr-fonts-style align-center mb-0 mt-2 display-5">Here you can find different kind of infromation which could be helpful</h5>
              <div class="row justify-content-center">

    {% for blog in blogs %}
    <div class="col-md-6">
        <div class="card mb-3">
            <div class="card-body">
                <a href="{% url 'blog:detail' blog.id %}">
                 <img class="img-fluid img-thumbnail mb-2" alt="..." src="{{ blog.image.url }}">
                    <h2>{{ blog.title }}</h2>
                 </a>
                <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
            </div>
        </div>
    </div>

{% endfor %}
  </div>
{% if blogs.has_other_pages %}
<div class="pagination">
    {% if blogs.has_previous %}
    <a href="?page=1">&laquo; First</a>
    <a href="?page={{ blogs.previous_page_number }}">previous</a>
    {% endif %}

    {% for i in blogs.paginator.page_range %}
    {% if blogs.number == i %}
    <span class="current-page">{{ i }}</span>
    {% else %}
    <a href="?page={{ i }}">{{ i }}</a>
    {% endif %}
    {% endfor %}

    {% if blogs.has_next %}
    <a href="?page={{ blogs.next_page_number }}">next</a>
    <a href="?page={{ blogs.paginator.num_pages }}">Last &raquo;</a>
    {% endif %}
</div>
{% endif %}
  </div>
        </div>
    </div>

</section>
{% endblock %}

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.description|safe }}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Site made with Mobirise Website Builder v5.7.8, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v5.7.8, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'images/nexus1.png' %}" type="image/x-icon">
  <meta name="description" content="">




  <title>Nexus Technology</title>
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons2/mobirise2.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/parallax/jarallax.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">



  <div>
    {% block content %}{% endblock %}
  </div>

</head>

<body>


 <section data-bs-version="5.1" class="menu menu2 cid-tzNsZcUNCy" once="menu" id="menu2-r">

    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg ">
        <div class="container">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="{% url 'home' %}">
                        <img src="{% static "portfolio/nexus1.png" %}" width="100" height="100" class="d-inline-block align-top" alt="Hilal's Logo">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-7" href="{% url 'home' %}"></a></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
                    <li class="nav-item"><a class="nav-link link text-black display-4" href="{% url 'home' %}"> About us</a></li>
                    <li class="nav-item"><a class="nav-link link text-black display-4" href="#services"> Services</a></li>
                    <li class="nav-item"><a class="nav-link link text-black display-4" href="#contact-section">Contacts</a>
                    </li>
                    <!-- <li class="nav-item"><a class="nav-link link text-black display-4"  href="{% url 'blog:all_blogs' %}">More</a></li> -->
                </ul>
            </div>
        </div>
    </nav>
</section>


<section data-bs-version="5.1" class="contacts1 cid-tzNujFWN9L" id="contacts1-t">





    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong></strong>
            </h3>
            <h4 class="mbr-section-subtitle mbr-fonts-style align-center mb-0 mt-2 display-5">
            </h4>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="card col-12 col-lg-6">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <div class="image-wrapper">
                            <span class="mbr-iconfont mobi-mbri-letter mobi-mbri"></span>
                        </div>
                        <h4 class="card-title mbr-fonts-style mb-2 display-2">
                            <strong>Email</strong>
                        </h4>
                        <p class="mbr-text mbr-fonts-style mb-2 display-4">
                            We will reply as soon as possible</p>
                        <h5 class="link mbr-fonts-style display-7"><a href="mailto:info@sharifli.com" class="text-primary">Send us an
                                email</a>
                        </h5>
                    </div>
                </div>
            </div>
            <div class="card col-12 col-lg-6">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <div class="image-wrapper">
                            <span class="mbr-iconfont mobi-mbri-mobile-2 mobi-mbri"></span>
                        </div>
                        <h4 class="card-title mbr-fonts-style align-center mb-2 display-2">
                            <strong>Phone</strong>
                        </h4>
                        <p class="mbr-text mbr-fonts-style mb-2 display-4">
                            Mon - Fri 09:00 - 18:00</p>
                        <h5 class="link mbr-black mbr-fonts-style display-7">
                            <a href="tel:+994702011328" class="text-primary">Call (+994) 70 201 13 28</a>
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section data-bs-version="5.1" class="footer7 cid-tzNtbDCISj" once="footers" id="footer7-s">





    <div id="contact-section" class="container">
        <div class="media-container-row align-center mbr-white">
            <div class="col-12">
                <p class="mbr-text mb-0 mbr-fonts-style display-7">
                    © Copyright 2023 - All Rights Reserved
                </p>
            </div>
        </div>
    </div>



</body>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<section class="header1 cid-s48MCQYojq mbr-fullscreen mbr-parallax-background" data-bs-version="5.1" id="header1-f">

<div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(255, 255, 255);"></div>

 <div class="align-center container">
          <div class="row justify-content-center">
            <div class="col-12 col-lg-8">
                <h1 class="mbr-section-title mbr-fonts-style mb-3 display-2"><b>Innovative solutions for seamless integration</b></h1>

                <p class="mbr-text mbr-fonts-style display-7"> We are dedicated to helping businesses of all sizes thrive by providing cutting-edge technology solutions tailored to their specific needs. Our team of experts is committed to delivering reliable and innovative solutions that will help your business operate more efficiently, increase productivity, and ultimately achieve your goals. We offer a wide range of services, including system integrations and custom software development, to ensure that your technology is working seamlessly to support your business. At our core, we are passionate about technology and its ability to drive success. Let us help you take your business to the next level with our expertise and innovative solutions.</p>

            </div>
        </div>

 </div>
</div>

</section>

<section data-bs-version="5.1" class="slider1 cid-tAbbPxSlov" id="slider1-k">

    <div class="carousel slide" id="tAlVxN7GZu" data-interval="5000" data-bs-interval="5000">
        <ol class="carousel-indicators">
            <li data-slide-to="0" data-bs-slide-to="0" class="active" data-target="#tAlVxN7GZu" data-bs-target="#tAlVxN7GZu"></li>
            <li data-slide-to="1" data-bs-slide-to="1" data-target="#tAlVxN7GZu" data-bs-target="#tAlVxN7GZu"></li>
            <li data-slide-to="2" data-bs-slide-to="2" data-target="#tAlVxN7GZu" data-bs-target="#tAlVxN7GZu"></li>

        </ol>
        <div class="carousel-inner">

            <div class="carousel-item slider-image item active">
                <div class="item-wrapper">
                    <img class="d-block w-100" src="{% static 'assets/images/mbr-1900x1069.jpg'%}" alt="Mobirise Website Builder">

                    <div class="carousel-caption">
                        <h5 class="mbr-section-subtitle mbr-fonts-style display-2"><strong>IT Infrastructure Administration</strong></h5>
                        <p class="mbr-section-text mbr-fonts-style display-7">We offer server administration — a service that allows you to give up routine infrastructure management to our experts. The service includes full OS support at the platform level, as well as support of a range of databases and application servers.</p>
                    </div>
                </div>
            </div>
            <div class="carousel-item slider-image item">
                <div class="item-wrapper">
                    <img class="d-block w-100" src="{% static 'assets/images/mbr-1620x1080.jpg'%}" alt="Mobirise Website Builder">

                    <div class="carousel-caption">
                        <h5 class="mbr-section-subtitle mbr-fonts-style display-2"><strong>IT Management Services</strong></h5>
                        <p class="mbr-section-text mbr-fonts-style display-7">We provide clients with 24/7/365 IT management service, which includes monitoring, support, maintenance and management of their IT infrastructure</p>
                    </div>
                </div>
            </div><div class="carousel-item slider-image item">
                <div class="item-wrapper">
                    <img class="d-block w-100" src="{% static 'assets/images/mbr-1900x1140.jpg'%}" alt="Mobirise Website Builder" data-slide-to="2" data-bs-slide-to="3">

                    <div class="carousel-caption">
                        <h5 class="mbr-section-subtitle mbr-fonts-style display-5"><strong>Contact Center</strong></h5>
                        <p class="mbr-section-text mbr-fonts-style display-7">Accelerate your businesses growth with 3CX phone system. Don’t just rely on phone calls! Use Live Chat, WhatsApp, Facebook, business SMS and Video Conferencing too. All this from a single client so no switching between apps.</p>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control carousel-control-prev" role="button" data-slide="prev" data-bs-slide="prev" href="#tAlVxN7GZu">
            <span class="mobi-mbri mobi-mbri-arrow-prev" aria-hidden="true"></span>
            <span class="sr-only visually-hidden">Previous</span>
        </a>
        <a class="carousel-control carousel-control-next" role="button" data-slide="next" data-bs-slide="next" href="#tAlVxN7GZu">
            <span class="mobi-mbri mobi-mbri-arrow-next" aria-hidden="true"></span>
            <span class="sr-only visually-hidden">Next</span>
        </a>
    </div>
</section>

<script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>  <script src="{% static 'assets/parallax/jarallax.js' %}"></script>  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %"}></script>  <script src="{% static 'assets/ytplayer/index.js' %"}></script>  <script src="{% static 'assets/dropdown/js/navbar-dropdown.js' %}"></script>  <script src="{% static 'assets/theme/js/script.js' %}"></script>


<section data-bs-version="5.1" class="features3 cid-tA3VKVutDo" id="features3-x">


    <div id="services" class="container">
        <div class="mbr-section-head">
            <h4 class="mbr-section-title mbr-fonts-style align-center mb-0 mt-4 display-2">
                <strong></strong></h4>
            <h5 class="mbr-section-subtitle mbr-fonts-style align-center mb-0 mt-2 display-5"></h5>
              <div class="row justify-content-center">

    {% for project in projects %}
        <div class="col-lg-4 col-md-6">

         <a href="{% url 'portfolio:project_detail' project.id %}" target="_blank">
             <img class="img-fluid img-thumbnail mb-2" alt="..." src="{{ project.image.url }}">
         </a>
        <h5 class="item-title mbr-fonts-style display-7"><strong>{{ project.title }}</strong></h5>
        <p class="mbr-text mbr-fonts-style mt-3 display-7">{{ project.description|striptags|truncatechars:100  }}</p>
        <div class="mt-2"><a href="{% url 'portfolio:project_detail' project.id %}" class="btn btn-primary item-btn  m-0" target="_blank">Learn More
                            &gt;</a></div>

        </div>
    {% endfor %}
  </div>
        </div>
    </div>
</section>

{% endblock %}

portfolio/templates/portfolio/index.html
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v5.7.8, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v5.7.8, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/logo.png" type="image/x-icon">
  <meta name="description" content="">
  
  
  <title>Home</title>
  <link rel="stylesheet" href="assets/web/assets/mobirise-icons2/mobirise2.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="assets/parallax/jarallax.css">
  <link rel="stylesheet" href="assets/dropdown/css/style.css">
  <link rel="stylesheet" href="assets/socicon/css/styles.css">
  <link rel="stylesheet" href="assets/theme/css/style.css">
  <link rel="preload" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>
  <link rel="preload" as="style" href="assets/mobirise/css/mbr-additional.css"><link rel="stylesheet" href="assets/mobirise/css/mbr-additional.css" type="text/css">

  
  
  
</head>
<body>
  
  <section data-bs-version="5.1" class="menu menu2 cid-tzNsZcUNCy" once="menu" id="menu2-r">
    
    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
        <div class="container">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="https://mobiri.se">
                        <img src="assets/images/logo.png" alt="Mobirise Website Builder" style="height: 3rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-7" href="https://mobiri.se">Mobirise</a></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
                    <li class="nav-item"><a class="nav-link link text-black display-4" href="https://mobiri.se">
                            About us</a></li>
                    <li class="nav-item"><a class="nav-link link text-black display-4" href="https://mobiri.se">
                            Services</a></li>
                    <li class="nav-item"><a class="nav-link link text-black display-4" href="https://mobiri.se">Contacts</a>
                    </li>
                </ul>
                
                <div class="navbar-buttons mbr-section-btn">
                    <a class="btn btn-primary display-4" href="https://mobiri.se">
                        Download Now</a>
                </div>
            </div>
        </div>
    </nav>
</section>

<section data-bs-version="5.1" class="header1 cid-s48MCQYojq mbr-fullscreen mbr-parallax-background" id="header1-f">

    

    <div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(255, 255, 255);"></div>

    <div class="align-center container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-8">
                <h1 class="mbr-section-title mbr-fonts-style mb-3 display-1"><strong>Full Screen Intro</strong></h1>
                
                <p class="mbr-text mbr-fonts-style display-7">This is a default project. Click any text to edit or style it. Select text to insert a <a href="http://mobirise.com">link</a>. Click the blue "Gear" icon at the top right corner to hide/show buttons, text, title, and change the block background. Click the red "+" button at the bottom right corner to add a new block. Use the top left menu to create new pages, sites, and add new themes and extensions.</p>
                <div class="mbr-section-btn mt-3"><a class="btn btn-success display-4" href="https://mobirise.com">Button 1</a> <a class="btn btn-success-outline display-4" href="https://mobirise.com">Button 2 &gt;</a></div>
            </div>
        </div>
    </div>
</section>

<section data-bs-version="5.1" class="contacts1 cid-tzNujFWN9L" id="contacts1-t">

    

    
    
    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong>Contacts</strong>
            </h3>
            <h4 class="mbr-section-subtitle mbr-fonts-style align-center mb-0 mt-2 display-5">
                Contacts Subtitle
            </h4>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="card col-12 col-lg-6">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <div class="image-wrapper">
                            <span class="mbr-iconfont mobi-mbri-letter mobi-mbri"></span>
                        </div>
                        <h4 class="card-title mbr-fonts-style mb-2 display-2">
                            <strong>Email</strong>
                        </h4>
                        <p class="mbr-text mbr-fonts-style mb-2 display-4">
                            We will reply as soon as possible</p>
                        <h5 class="link mbr-fonts-style display-7"><a href="mailto:info@site.com" class="text-primary">Send us an
                                email</a>
                        </h5>
                    </div>
                </div>
            </div>
            <div class="card col-12 col-lg-6">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <div class="image-wrapper">
                            <span class="mbr-iconfont mobi-mbri-mobile-2 mobi-mbri"></span>
                        </div>
                        <h4 class="card-title mbr-fonts-style align-center mb-2 display-2">
                            <strong>Phone</strong>
                        </h4>
                        <p class="mbr-text mbr-fonts-style mb-2 display-4">
                            Mon - Fri 09:00 - 18:00</p>
                        <h5 class="link mbr-black mbr-fonts-style display-7">
                            <a href="tel:+12345678910" class="text-primary">Call (800) 123 45 67</a>
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section data-bs-version="5.1" class="footer7 cid-tzNtbDCISj" once="footers" id="footer7-s">

    

    

    <div class="container">
        <div class="media-container-row align-center mbr-white">
            <div class="col-12">
                <p class="mbr-text mb-0 mbr-fonts-style display-7">
                    © Copyright 2025 Mobirise - All Rights Reserved
                </p>
            </div>
        </div>
    </div>
</section><section class="display-7" style="padding: 0;align-items: center;justify-content: center;flex-wrap: wrap;    align-content: center;display: flex;position: relative;height: 4rem;"><a href="https://mobiri.se/2934668" style="flex: 1 1;height: 4rem;position: absolute;width: 100%;z-index: 1;"><img alt="" style="height: 4rem;" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="></a><p style="margin: 0;text-align: center;" class="display-7">Created with &#8204;</p><a style="z-index:1" href="https://mobirise.com/offline-website-builder.html">Offline Website Maker</a></section><script src="assets/bootstrap/js/bootstrap.bundle.min.js"></script>  <script src="assets/parallax/jarallax.js"></script>  <script src="assets/smoothscroll/smooth-scroll.js"></script>  <script src="assets/ytplayer/index.js"></script>  <script src="assets/dropdown/js/navbar-dropdown.js"></script>  <script src="assets/theme/js/script.js"></script>  
  
  
</body>
</html>

portfolio/templates/portfolio/project.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/project.css' %}">
  <div class="container">
    <div class="project-image">
      <img src="{{ project.image.url }}" alt="{{ project.title }}">
    </div>
    <div class="project-details">
      <h1 class="project-title">{{ project.title }}</h1>
      <p class="project-description">{{ project.description }}</p>
    </div>
  </div>
{% endblock %}